**Примеры из раздела 2.2**

*Кортеж (Tuple)* - структура данных (контейнер) в виде неизменяемой индексируемой
последовательности элементов какого-либо типа (элементы индексируются с единицы).
Синтаксис определения кортежа: ```(element1, element2, ...)```

Примеры кортежей:

In [1]:
# пустой кортеж:
()

()

In [2]:
# кортеж из элементов типа String:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [3]:
# кортеж из целых чисел:
x1 = (1, 2, 3)

(1, 2, 3)

In [4]:
# кортеж из элементов разных типов:
x2 = (1, 2.0, "tmp")

(1, 2.0, "tmp")

In [5]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

Примеры операций над кортежами:

In [6]:
# длина кортежа x2:
length(x2)

3

In [7]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [8]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
с = x1[2] + x1[3]

5

In [9]:
# обращение к элементам именованного кортежа x3:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [10]:
# проверка вхождения элементов tmp и 0 в кортеж x2
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

*Словарь* - неупорядоченный набор связанных между собой по ключу данных.
Синтаксис определения словаря: ```Dict(key1 => value1, key2 => value2, ...)```

Примеры словарей и операций над ними:

In [11]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [12]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [13]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [14]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [15]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [16]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [17]:
pairs(phonebook)

Dict{String, Any} with 3 entries:
  "Сидоров П.С." => "555-3344"
  "Бухгалтерия"  => "555-2368"
  "Иванов И.И."  => ("867-5309", "333-5544")

In [18]:
# удалить ключ и связанные с ним значения из словаря:
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [19]:
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Сидоров П.С." => "555-3344"
  "Бухгалтерия"  => "555-2368"

In [20]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

*Множество*, как структура данных в Julia, соответствует множеству, как математическому объекту, то есть является неупорядоченной совокупностью элементов какого-либо
типа. Возможные операции над множествами: объединение, пересечение, разность;
принадлежность элемента множеству.
Синтаксис определения множества: ```Set([itr])```, где ```itr``` - набор значений, сгенерированных данным итерируемым объектом или пустое
множество.

Примеры множеств и операций над ними:

In [21]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [22]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [23]:
# проверка эквивалентности двух множеств:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [24]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [25]:
# объединение множеств:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [26]:
# пересечение множеств:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [27]:
# разность множеств:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [28]:
# проверка вхождения элементов одного множества в другое:
issubset(S1,S4)

true

In [29]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [30]:
# удаление последнего элемента множества:
pop!(S4)

2

*Массив* — коллекция упорядоченных элементов, размещённая в многомерной сетке.
Векторы и матрицы являются частными случаями массивов.
Общий синтаксис одномерных массивов:
```
array_name_1 = [element1, element2, ...]
array_name_2 = [element1 element2 ...]
```

Примеры массивов:

In [31]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [32]:
# создание пустого массива с конкретным типом:
empty_array_2 = (Int64)[]

Int64[]

In [33]:
# создание пустого массива с конкретным типом:
empty_array_3 = (Float64)[]

Float64[]

In [34]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [35]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [36]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [37]:
# многомерные массивы (матрицы):
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [38]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.681444  0.18759  0.51797  0.366196  0.193797  0.986055  0.570232  0.106307

In [39]:
# многомерный массив $2 \times 3$ (2 строки, 3 столбца) элементов
# со значениями, случайно распределёнными на интервале [0, 1):
C = rand(2,3)

2×3 Matrix{Float64}:
 0.682008  0.0358172  0.33128
 0.84213   0.197709   0.0111639

In [40]:
# трёхмерный массив:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.0562923  0.226626  0.107457
 0.875085   0.60193   0.253301
 0.895195   0.180269  0.541867
 0.86347    0.655776  0.146883

[:, :, 2] =
 0.746524    0.3816    0.0562651
 0.00189321  0.449544  0.957292
 0.46053     0.571365  0.754601
 0.251139    0.514296  0.627787

Примеры массивов, заданных некоторыми функциями через включение:

In [41]:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [42]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно)
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [43]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

Некоторые операции для работы с массивами:
- ```length(A)``` — число элементов массива A;
- ```ndims(A)``` — число размерностей массива A;
- ```size(A)``` — кортеж размерностей массива A;
- ```size(A, n)``` — размерность массива A в заданном направлении;
- ```copy(A)``` — создание копии массива A;
- ```ones(), zeros()``` — создать массив с единицами или нулями соответственно;
- ```fill(value,array_name)``` — заполнение массива заранее определенным значением;
- ```sort()``` — сортировка элементов;
- ```collect()``` — вернуть массив всех элементов в коллекции или итераторе;
- ```reshape()``` — изменение размера массива;
- ```transpose()``` — транспонирование массива;

Несколько примеров:

In [44]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [45]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [46]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [47]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [48]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)

6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [49]:
# заполнение массива посредством функции repeat():
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [50]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив 2x6
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [51]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [52]:
# транспонирование
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [53]:
# массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 13  15  19  20  19
 19  18  15  10  10
 20  12  11  15  14
 13  20  18  14  10
 15  20  12  15  16
 18  10  13  13  15
 19  16  16  19  16
 10  10  16  19  16
 19  20  17  20  10
 12  15  10  10  20

In [54]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 15
 18
 12
 20
 20
 10
 16
 10
 20
 15

In [55]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 15  19
 18  10
 12  14
 20  10
 20  16
 10  15
 16  16
 10  16
 20  10
 15  20

In [56]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 15  19  20
 18  15  10
 12  11  15
 20  18  14
 20  12  15
 10  13  13
 16  16  19
 10  16  19
 20  17  20
 15  10  10

In [57]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 19  10
 13  10
 18  15

In [58]:
# значения в строке 1 от столбца 3 до последнего столбца:
ar[1, 3:end]

3-element Vector{Int64}:
 19
 20
 19

In [59]:
# сортировка по столбцам:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 10  10  10  10  10
 12  10  11  10  10
 13  12  12  13  10
 13  15  13  14  14
 15  15  15  15  15
 18  16  16  15  16
 19  18  16  19  16
 19  20  17  19  16
 19  20  18  20  19
 20  20  19  20  20

In [60]:
# сортировка по строкам:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 13  15  19  19  20
 10  10  15  18  19
 11  12  14  15  20
 10  13  14  18  20
 12  15  15  16  20
 10  13  13  15  18
 16  16  16  19  19
 10  10  16  16  19
 10  17  19  20  20
 10  10  12  15  20

In [61]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 0  1  1  1  1
 1  1  1  0  0
 1  0  0  1  0
 0  1  1  0  0
 1  1  0  1  1
 1  0  0  0  1
 1  1  1  1  1
 0  0  1  1  1
 1  1  1  1  0
 0  1  0  0  1

In [62]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

31-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(5, 1)
 CartesianIndex(6, 1)
 CartesianIndex(7, 1)
 CartesianIndex(9, 1)
 CartesianIndex(1, 2)
 CartesianIndex(2, 2)
 CartesianIndex(4, 2)
 CartesianIndex(5, 2)
 CartesianIndex(7, 2)
 CartesianIndex(9, 2)
 CartesianIndex(10, 2)
 ⋮
 CartesianIndex(1, 4)
 CartesianIndex(3, 4)
 CartesianIndex(5, 4)
 CartesianIndex(7, 4)
 CartesianIndex(8, 4)
 CartesianIndex(9, 4)
 CartesianIndex(1, 5)
 CartesianIndex(5, 5)
 CartesianIndex(6, 5)
 CartesianIndex(7, 5)
 CartesianIndex(8, 5)
 CartesianIndex(10, 5)

**Задания для самостоятельного выполнения**

**Задание №1**

Даны множества: 𝐴 = {0, 3, 4, 9}, 𝐵 = {1, 3, 4, 7}, 𝐶 = {0, 1, 2, 4, 7, 8, 9}. Найти P = 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐶 ∪ 𝐵 ∩ 𝐶.

In [63]:
A = Set([0, 3, 4, 9]);
B = Set([1, 3, 4, 7]);
C = Set([0, 1, 2, 4, 7, 8, 9]);
P = union(intersect(A, B), intersect(A, B), intersect(A, C), intersect(B, C))

Set{Int64} with 6 elements:
  0
  4
  7
  9
  3
  1

**Задание №2**

Приведите свои примеры с выполнением операций над множествами элементов разных типов.

In [64]:
Set1 = Set([12, 68, 4, "Alyona"])

Set{Any} with 4 elements:
  4
  68
  12
  "Alyona"

In [65]:
println("\nЭлементы множества:")
for i in Set1
    println(i)
end


Элементы множества:
4
68
12
Alyona


In [66]:
println(in("ALyona", Set1))

false


In [67]:
Set1 = push!(Set1, "Good")
println("\nМножество после добавления одного элемента:\n", Set1)


Множество после добавления одного элемента:
Set(Any[4, 68, "Good", 12, "Alyona"])


In [68]:
for i in 1:4
    push!(Set1, i)
end
println("\nМножество после добавления диапазона элементов:\n", Set1)


Множество после добавления диапазона элементов:
Set(Any[4, 2, 68, "Good", 12, "Alyona", 3, 1])


**Задание №3**

Создать массив разными способами

In [69]:
a_1 = [i for i in 1:25]
print(a_1, '\n')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


In [70]:
b_1 = reverse([i for i in 1:25])
print(b_1, '\n')

[25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [71]:
c_1 = vcat(a_1, b_1)
print(c_1, '\n')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [72]:
tmp = [4, 6, 3]
print(tmp, '\n')

[4, 6, 3]


In [73]:
println(vcat(fill.(tmp, [10, 1, 1])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 3]


In [74]:
println(vcat(fill.(tmp, [10, 10, 10])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [75]:
println(vcat(fill.(tmp, [11, 10, 10])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [76]:
println(vcat(fill.(tmp, [10, 20, 30])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [77]:
tmp_1 = []
for i in 1:3
    push!(tmp_1, 2^tmp[i])
end
println(vcat(fill.(tmp_1, [1, 1, 4])...))
count = 0
for i in tmp_1
    if '6' in string(i)
        count += 1
    end
end
println(count)

[16, 64, 8, 8, 8, 8]
2


In [78]:
using Statistics
y(x) = exp(x)*cos(x)
Y = [y(x) for x in 3:0.1:6]
mean(Y)

53.11374594642971

In [79]:
vect = []
for j in 1:3:34
    i = j + 2
    push!(vect, ((0.1)^i, (0.2)^j))
end
println(vect)

Any[(0.0010000000000000002, 0.2), (1.0000000000000004e-6, 0.0016000000000000003), (1.0000000000000005e-9, 1.2800000000000006e-5), (1.0000000000000008e-12, 1.0240000000000006e-7), (1.0000000000000009e-15, 8.192000000000005e-10), (1.0000000000000008e-18, 6.5536000000000055e-12), (1.0000000000000012e-21, 5.2428800000000056e-14), (1.0000000000000012e-24, 4.194304000000005e-16), (1.0000000000000015e-27, 3.3554432000000044e-18), (1.0000000000000017e-30, 2.684354560000004e-20), (1.0000000000000018e-33, 2.147483648000004e-22), (1.000000000000002e-36, 1.7179869184000035e-24)]


In [80]:
vect_1 = [(2^i)/i for i in 1:25]
println(vect_1)

[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]


In [81]:
vect_2 = []
for i in 1:30
    push!(vect_2, "fn$i")
end
println(vect_2)

Any["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]


In [82]:
vect_x = []
for i in 1:250
    push!(vect_x, rand(0:999))
end
println(vect_x)

vect_y = []
for i in 1:250
    push!(vect_y, rand(0:999))
end
println(vect_y)

Any[139, 845, 236, 686, 811, 929, 869, 583, 920, 743, 110, 948, 977, 609, 338, 685, 775, 22, 639, 271, 327, 107, 77, 580, 856, 370, 206, 878, 903, 381, 707, 95, 501, 174, 250, 533, 970, 933, 356, 418, 302, 593, 23, 686, 984, 193, 349, 315, 294, 600, 876, 19, 405, 307, 180, 915, 331, 959, 767, 450, 921, 377, 812, 708, 24, 585, 6, 40, 530, 31, 753, 783, 37, 597, 701, 543, 109, 865, 381, 242, 731, 676, 891, 720, 133, 705, 831, 595, 989, 253, 207, 439, 881, 968, 370, 363, 315, 832, 746, 189, 418, 17, 422, 85, 408, 604, 892, 477, 857, 895, 70, 521, 719, 747, 341, 907, 637, 168, 101, 511, 720, 754, 415, 490, 5, 952, 84, 526, 205, 373, 506, 241, 66, 608, 661, 538, 648, 901, 792, 79, 791, 18, 983, 148, 659, 477, 16, 456, 31, 562, 419, 383, 328, 847, 493, 157, 283, 426, 42, 328, 124, 170, 365, 606, 697, 350, 271, 312, 688, 14, 676, 480, 808, 264, 966, 230, 860, 585, 464, 156, 191, 96, 408, 509, 944, 518, 864, 87, 462, 639, 179, 810, 749, 763, 164, 494, 237, 200, 600, 563, 603, 8, 964, 331, 446,

In [83]:
vect_3 = []
for i in 1:249
    j = i + 1
    push!(vect_3, vect_y[j] - vect_x[i])
end
println(vect_3)

Any[780, -576, 225, -629, -309, -721, -546, 222, -556, 94, 820, -392, -849, -251, 205, -15, -398, 822, -495, 209, -82, 821, 383, 244, -293, 493, 409, -711, -834, -160, -696, 641, 482, 298, -9, 44, -734, -688, 226, 301, -177, -104, 141, -71, -474, 29, 96, 467, 178, 48, -67, 629, 564, -47, 18, -602, 464, -114, -433, 233, -377, 208, -665, -164, 417, -377, 39, 245, 238, 180, 136, -512, 425, 5, 167, 406, 733, -96, -72, -210, -313, -536, -771, -328, 342, 46, -320, 9, -201, 555, 207, 121, -217, -207, 24, -331, -87, 68, -134, 552, -31, 882, 258, -65, -122, -126, -302, 409, -689, -742, 551, -237, -411, -47, 287, -404, -579, 736, 772, 411, 254, -378, 313, 184, 605, -192, 279, 371, -130, -157, 438, 756, 175, 125, -158, -424, 33, -93, 152, 401, -352, 205, -256, 220, 51, 45, 347, 123, 816, -137, 121, 457, 441, -50, 475, -64, 554, -221, 298, 497, 242, 774, 452, 246, -129, -236, 107, -104, -28, 124, -575, 513, -575, 193, -740, 292, 49, 368, -288, 757, 525, 766, 407, -374, -527, -102, -20, 68, 342, -3

In [84]:
vect_4 = []
for i in 1:248
    j = i + 1
    push!(vect_4, vect_x[i] + 2*vect_x[i + 1] - vect_x[i + 2])
end
println(vect_4)

Any[1593, 631, 797, 1379, 1800, 2084, 1115, 1680, 2296, 15, 1029, 2293, 1857, 600, 933, 2213, 180, 1029, 854, 818, 464, -319, 381, 1922, 1390, -96, 1059, 2303, 958, 1700, 396, 923, 599, 141, 346, 1540, 2480, 1227, 890, 429, 1465, -47, 411, 2461, 1021, 576, 685, 303, 618, 2333, 509, 522, 839, -248, 1679, 618, 1482, 2043, 746, 1915, 863, 1293, 2204, 171, 1188, 557, -444, 1069, -161, 754, 2282, 260, 530, 1456, 1678, -104, 1458, 1385, 134, 1028, 1192, 1738, 2198, 281, 712, 1772, 1032, 2320, 1288, 228, 204, 1233, 2447, 1345, 781, 161, 1233, 2135, 706, 1008, 30, 776, 184, 297, 724, 1911, 989, 1296, 2577, 514, 393, 1212, 1872, 522, 1518, 2013, 872, -141, 403, 1197, 1813, 1094, 1390, -452, 1825, 594, 931, 563, 445, 1144, 922, -235, 621, 1392, 1089, 933, 1658, 2406, 159, 1643, -156, 1836, 620, 989, 1597, 53, 897, -44, 736, 1017, 857, 192, 1529, 1676, 524, 297, 1093, 182, 574, 406, 99, 294, 880, 1650, 1126, 580, 207, 1674, 40, 886, 828, 1832, 370, 1966, 566, 1365, 1566, 1357, 585, 442, -25, 403,

In [85]:
vect_5 = []
for i in 1:249
    j = i + 1
    push!(vect_5, sin(vect_y[i])/cos(vect_x[j]))
end
println(vect_5)

Any[-0.7880592091617693, -1.0732411117691343, -2.1773018896346663, 0.8151794315452525, 0.7119665629909786, 1.777893991451243, 2.6205741851910234, -0.6238239585471654, -51.23372327983299, 0.4124949291643564, 1.3431350227199004, -0.08851395516538663, 0.06934746263406513, 2.620122952869077, -0.14234352413428672, -0.8453227096341271, 0.7451825594458944, -0.02874578432905314, 1.3027868168732726, -0.5101005270471175, 0.6268106552282097, 1.4273613538869274, 2.565812792780919, 11.567937323446563, 1.0333157456398765, -2.721950838772453, -10.740652432802223, 3.310263568353763, 0.7351258014507467, 0.11594613176262844, 1.213326317474049, 11.914659476047378, -2.174072409187203, 1.2994111831335509, 1.4385188752490297, -1.0749434631044543, 0.8701586063765411, 0.6874846248674931, 0.04484526096476261, -0.7852579468112049, -0.5690394811983434, 1.156160439912668, -2.088799447698136, -0.7660450043121223, 3.3093177184578204, -0.90956191952463, 1.3029397388543524, -3.4632957358664105, -0.2540130971798484, -

In [86]:
summa = 0
for i in 1: 249
    summa += exp(-vect_x[i + 1])/(vect_x[i] + 10)
end 
print(summa)

1.8434899677237637e-5

In [87]:
y_sorted = sort(vect_y)
for i in y_sorted
    if i > 600
        print(i, "; ")
    end
end
println('\n', "Индексы:")
show(findall(vect_y .> 600))

602; 604; 610; 612; 615; 615; 621; 628; 642; 648; 648; 660; 664; 670; 674; 680; 681; 683; 699; 700; 710; 716; 719; 727; 727; 728; 729; 731; 733; 736; 741; 747; 751; 760; 761; 768; 769; 769; 769; 782; 788; 795; 797; 799; 804; 805; 808; 808; 809; 815; 817; 824; 825; 837; 837; 840; 842; 844; 844; 845; 847; 852; 862; 863; 868; 873; 876; 883; 886; 887; 889; 897; 899; 900; 900; 904; 909; 913; 919; 922; 928; 930; 944; 944; 944; 949; 953; 957; 964; 968; 969; 974; 977; 979; 983; 985; 993; 994; 997; 
Индексы:
[2, 9, 11, 12, 17, 19, 23, 25, 27, 28, 33, 34, 41, 45, 49, 51, 52, 53, 54, 58, 59, 61, 70, 72, 75, 76, 77, 78, 79, 87, 89, 90, 91, 94, 95, 99, 100, 101, 103, 104, 109, 112, 115, 116, 119, 120, 121, 122, 124, 125, 126, 127, 129, 132, 133, 135, 138, 139, 140, 144, 146, 150, 153, 154, 155, 156, 158, 161, 163, 164, 165, 170, 173, 178, 179, 181, 182, 183, 184, 188, 190, 199, 202, 206, 209, 211, 213, 215, 216, 220, 225, 226, 227, 231, 232, 234, 236, 242, 248]

In [88]:
for i in 1:length(vect_y)
    if (vect_y[i] > 600)
        print(vect_x[i], "; ")
    end
end

845; 920; 110; 948; 775; 639; 77; 856; 206; 878; 501; 174; 302; 984; 294; 876; 19; 405; 307; 959; 767; 921; 31; 783; 701; 543; 109; 865; 381; 831; 989; 253; 207; 968; 370; 746; 189; 418; 422; 85; 857; 521; 341; 907; 101; 511; 720; 754; 490; 5; 952; 84; 205; 241; 66; 661; 901; 792; 79; 148; 477; 562; 328; 847; 493; 157; 426; 124; 365; 606; 697; 14; 808; 585; 464; 191; 96; 408; 509; 87; 639; 600; 8; 240; 999; 211; 874; 44; 313; 273; 564; 761; 385; 399; 677; 633; 563; 344; 592; 

In [89]:
vect_6 = []
for i in vect_x
    push!(vect_6, abs(i - mean(vect_x))^(1/2))
end
print(vect_6)

Any[18.703796406077565, 18.872413730098224, 15.900691808849073, 14.041652324423932, 17.94903897148814, 20.980181124099, 19.497897322531987, 9.70401978563523, 20.764585235443544, 15.942647208039197, 19.463607065495335, 21.4282057111649, 22.094524208500168, 10.962116583944908, 12.28136800197763, 14.00599871483644, 16.916500820205105, 21.606295378893623, 12.254305365870398, 14.759132765850438, 12.721320686155192, 19.540521999168803, 20.29364432525612, 9.548193546425418, 19.161628323292362, 10.901009127599151, 16.81760981828274, 19.727341432641147, 20.35111790541247, 10.384218795845936, 14.770511162447967, 19.845200931207525, 3.4882660448996727, 17.743505854255524, 15.454190370252334, 6.645900992341069, 21.93554193540702, 21.07529359226106, 11.525276569349648, 8.416174903125528, 13.668650262553358, 10.206272581114028, 21.583141569289676, 14.041652324423932, 22.25237066022405, 17.199767440288255, 11.825058139391958, 13.184536396855218, 13.958223382651532, 10.543623665514623, 19.676585069569

In [90]:
count = 0
for i in vect_y
    if abs(maximum(vect_y) - i) <= 200
        count += 1
    end
end
print(count)

57

In [91]:
sum_even = 0
sum_odd = 0
for i in vect_x
    if (i % 2) == 0
        sum_even += 1
    else
        sum_odd += 1
    end
end
println("Количество чётных элементов вектора x: ", sum_even)
println("Количество нечётных элементов вектора x: ", sum_odd)

Количество чётных элементов вектора x: 118
Количество нечётных элементов вектора x: 132


In [92]:
sum_seven = 0
for i in vect_x
    if (i % 7) == 0
        sum_seven += 1
    end
end
println("Количество элементов вектора x кратных 7: ", sum_seven)

Количество элементов вектора x кратных 7: 37


In [93]:
print(vect_x)

Any[139, 845, 236, 686, 811, 929, 869, 583, 920, 743, 110, 948, 977, 609, 338, 685, 775, 22, 639, 271, 327, 107, 77, 580, 856, 370, 206, 878, 903, 381, 707, 95, 501, 174, 250, 533, 970, 933, 356, 418, 302, 593, 23, 686, 984, 193, 349, 315, 294, 600, 876, 19, 405, 307, 180, 915, 331, 959, 767, 450, 921, 377, 812, 708, 24, 585, 6, 40, 530, 31, 753, 783, 37, 597, 701, 543, 109, 865, 381, 242, 731, 676, 891, 720, 133, 705, 831, 595, 989, 253, 207, 439, 881, 968, 370, 363, 315, 832, 746, 189, 418, 17, 422, 85, 408, 604, 892, 477, 857, 895, 70, 521, 719, 747, 341, 907, 637, 168, 101, 511, 720, 754, 415, 490, 5, 952, 84, 526, 205, 373, 506, 241, 66, 608, 661, 538, 648, 901, 792, 79, 791, 18, 983, 148, 659, 477, 16, 456, 31, 562, 419, 383, 328, 847, 493, 157, 283, 426, 42, 328, 124, 170, 365, 606, 697, 350, 271, 312, 688, 14, 676, 480, 808, 264, 966, 230, 860, 585, 464, 156, 191, 96, 408, 509, 944, 518, 864, 87, 462, 639, 179, 810, 749, 763, 164, 494, 237, 200, 600, 563, 603, 8, 964, 331, 446,

In [94]:
print(vect_y)

Any[114, 919, 269, 461, 57, 502, 208, 323, 805, 364, 837, 930, 556, 128, 358, 543, 670, 377, 844, 144, 480, 245, 928, 460, 824, 563, 863, 615, 167, 69, 221, 11, 736, 983, 472, 241, 577, 236, 245, 582, 719, 125, 489, 164, 615, 510, 222, 445, 782, 472, 648, 809, 648, 969, 260, 198, 313, 795, 845, 334, 683, 544, 585, 147, 544, 441, 208, 45, 285, 768, 211, 889, 271, 462, 602, 868, 949, 842, 769, 309, 32, 418, 140, 120, 392, 475, 751, 511, 604, 788, 808, 414, 560, 664, 761, 394, 32, 228, 900, 612, 741, 387, 899, 680, 20, 286, 478, 590, 886, 168, 153, 621, 284, 308, 700, 628, 503, 58, 904, 873, 922, 974, 376, 728, 674, 610, 760, 363, 897, 75, 216, 944, 997, 241, 733, 503, 114, 681, 808, 944, 480, 439, 223, 727, 368, 710, 522, 363, 579, 847, 425, 540, 840, 769, 797, 968, 93, 837, 205, 340, 825, 366, 944, 817, 852, 568, 114, 378, 208, 660, 138, 101, 993, 233, 457, 226, 522, 909, 953, 176, 913, 716, 862, 815, 135, 417, 416, 844, 155, 804, 240, 486, 525, 341, 364, 156, 317, 376, 799, 427, 431, 9

In [95]:
p = sortperm(vect_y)
vect_x_sorted = vect_x[p]

250-element Vector{Any}:
 709
  95
  10
 408
 874
 731
 315
  40
 811
 168
 578
 381
 373
   ⋮
 563
 313
 157
 307
 754
   8
 633
 174
 874
 808
 999
  66

In [96]:
reverse(last(sort(vect_x), 10))

10-element Vector{Any}:
 999
 995
 989
 984
 983
 977
 971
 970
 968
 966

In [97]:
x_sorted = sort(vect_x)
print(x_sorted)

Any[5, 6, 8, 10, 14, 16, 16, 17, 18, 19, 22, 23, 24, 29, 31, 31, 37, 40, 42, 44, 66, 70, 75, 77, 79, 84, 85, 87, 95, 96, 101, 107, 109, 110, 124, 133, 139, 148, 156, 157, 164, 166, 168, 170, 174, 176, 179, 180, 189, 191, 193, 200, 205, 206, 207, 211, 217, 221, 230, 236, 237, 240, 241, 242, 250, 253, 262, 264, 271, 271, 273, 283, 290, 294, 294, 302, 307, 310, 312, 313, 315, 315, 327, 328, 328, 331, 331, 338, 341, 344, 349, 350, 356, 360, 363, 365, 370, 370, 373, 377, 381, 381, 383, 385, 399, 405, 408, 408, 415, 418, 418, 419, 422, 426, 435, 439, 446, 450, 456, 461, 462, 464, 471, 477, 477, 480, 490, 493, 494, 501, 506, 509, 511, 518, 521, 526, 529, 530, 533, 538, 543, 562, 563, 563, 564, 578, 580, 583, 585, 585, 592, 593, 595, 597, 600, 600, 603, 604, 606, 608, 609, 633, 637, 639, 639, 648, 659, 659, 661, 676, 676, 677, 685, 686, 686, 688, 697, 701, 704, 705, 707, 708, 709, 719, 720, 720, 728, 731, 743, 746, 747, 749, 753, 754, 761, 763, 767, 775, 783, 791, 792, 808, 810, 811, 812, 820,

In [98]:
show(unique(x_sorted))

Any[5, 6, 8, 10, 14, 16, 17, 18, 19, 22, 23, 24, 29, 31, 37, 40, 42, 44, 66, 70, 75, 77, 79, 84, 85, 87, 95, 96, 101, 107, 109, 110, 124, 133, 139, 148, 156, 157, 164, 166, 168, 170, 174, 176, 179, 180, 189, 191, 193, 200, 205, 206, 207, 211, 217, 221, 230, 236, 237, 240, 241, 242, 250, 253, 262, 264, 271, 273, 283, 290, 294, 302, 307, 310, 312, 313, 315, 327, 328, 331, 338, 341, 344, 349, 350, 356, 360, 363, 365, 370, 373, 377, 381, 383, 385, 399, 405, 408, 415, 418, 419, 422, 426, 435, 439, 446, 450, 456, 461, 462, 464, 471, 477, 480, 490, 493, 494, 501, 506, 509, 511, 518, 521, 526, 529, 530, 533, 538, 543, 562, 563, 564, 578, 580, 583, 585, 592, 593, 595, 597, 600, 603, 604, 606, 608, 609, 633, 637, 639, 648, 659, 661, 676, 677, 685, 686, 688, 697, 701, 704, 705, 707, 708, 709, 719, 720, 728, 731, 743, 746, 747, 749, 753, 754, 761, 763, 767, 775, 783, 791, 792, 808, 810, 811, 812, 820, 831, 832, 845, 847, 856, 857, 860, 864, 865, 869, 874, 876, 878, 881, 891, 892, 895, 901, 903, 90

**Задание №4**

Создайте массив squares, в котором будут храниться квадраты всех целых чисел от 1 до 100.

In [99]:
squares = [(i)^2 for i in 1:100]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]

**Задание №5**

Подключите пакет Primes (функции для вычисления простых чисел). Сгенерируйте
массив myprimes, в котором будут храниться первые 168 простых чисел. Определите
89-е наименьшее простое число. Получите срез массива с 89-го до 99-го элемента
включительно, содержащий наименьшие простые числа.

In [100]:
import Pkg
Pkg.add("Primes")

     Project No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
    Manifest No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`


In [101]:
using Primes
myprimes = primes(prime(168))
print(myprimes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]

In [102]:
myprimes[89]

461

In [103]:
myprimes[89:99]

11-element Vector{Int64}:
 461
 463
 467
 479
 487
 491
 499
 503
 509
 521
 523

**Задание №6**

Вычислить выражения

In [104]:
sum_61 = 0
for i in 10:100
    sum_61 += i^3 + 4*i^2
end
print(sum_61)

26852735

In [105]:
M = 25
sum_62 = 0
for i in 1:M
    sum_62 += (2^(i)/i) + (3^(i)/i^2)
end
print(sum_62)

2.1291704368143802e9

In [106]:
N = 38
sum_63 = 1
a_n = 1
for i in 2:2:N
    a_n *= i/(i+1)
    sum_63 += a_n
end
print(sum_63)

6.976346137897618