In [1]:
2+3

5

In [2]:
1+2

3

In [3]:
3+4

7

In [4]:
?println

search: println print sprint pointer printstyled



```julia
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


In [5]:
println("Hello, world")

Hello, world


In [6]:
;date

Wed Sep  9 01:30:05 PM CEST 2026


In [7]:
;whoami

aabogatkina


In [8]:
typeof(3), typeof(3.5), typeof(3/3.5), typeof(sqrt(3+4im)), typeof(pi)

(Int64, Float64, Float64, ComplexF64, Irrational{:π})

In [9]:
1.0/0.0, 1.0/(-0.0), 0.0/0.0

(Inf, -Inf, NaN)

In [11]:
for T in
    [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128]
println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


In [12]:
Int64(2.0), Char(2)

(2, '\x02')

In [14]:
convert(Int64, 2.0), convert(Char, 2)

(2, '\x02')

In [16]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [17]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [18]:
f(8)

64

In [19]:
f(2)

4

In [20]:
g(x) = x^2

g (generic function with 1 method)

In [21]:
g(7)

49

In [22]:
g(11)

121

In [23]:
n = open("test.txt", "r")

IOStream(<file test.txt>)

In [25]:
read(n, String)

"Hello\nmy\nname\nis\nAlyona"

In [26]:
n = open("test.txt", "r")

IOStream(<file test.txt>)

In [27]:
readline(n)

"Hello"

In [28]:
n = open("test.txt", "r")

IOStream(<file test.txt>)

In [29]:
readlines(n)

5-element Vector{String}:
 "Hello"
 "my"
 "name"
 "is"
 "Alyona"

In [30]:
a = [4 7 6] # вектор-строка
b = [1, 2, 3] # вектор-столбец
a[2], b[2] # вторые элементы векторов a и b

(7, 2)

In [31]:
a = 1; b = 2; c = 3; d = 4 # присвоение значений
Am = [a b; c d] # матрица 2 х 2

2×2 Matrix{Int64}:
 1  2
 3  4

In [32]:
Am[1,1], Am[1,2], Am[2,1], Am[2,2] # элементы матрицы

(1, 2, 3, 4)

In [33]:
aa = [1 2]
AA = [1 2; 3 4]
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

In [34]:
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [36]:
using DelimitedFiles
n = open("test2.txt", "r")
readdlm(n)

3×3 Matrix{Any}:
 "X,"  "Y,"   "Z"
 "1,"  "2,"  3
 "1,"  "5,"  6

In [37]:
for i in 1:6
    print(i)
end

123456

In [38]:
for i in 1:6
    println(i)
end

1
2
3
4
5
6


In [39]:
show("Alyona")

"Alyona"

In [40]:
print("Alyona")

Alyona

In [41]:
?write()

```julia
write(filename::AbstractString, content)
```

Write the canonical binary representation of `content` to a file, which will be created if it does not exist yet or overwritten if it does exist.

Return the number of bytes written into the file.

---

```julia
write(io::IO, x)
```

Write the canonical binary representation of a value to the given I/O stream or file. Return the number of bytes written into the stream. See also [`print`](@ref) to write a text representation (with an encoding that may depend upon `io`).

The endianness of the written value depends on the endianness of the host system. Convert to/from a fixed endianness when writing/reading (e.g. using  [`htol`](@ref) and [`ltoh`](@ref)) to get results that are consistent across platforms.

You can write multiple values with the same `write` call, i.e. the following are equivalent:

```julia
write(io, x, y...)
write(io, x) + write(io, y...)
```

# Examples

Consistent serialization:

```jldoctest
julia> fname = tempname(); # random temporary filename

julia> open(fname,"w") do f
           # Make sure we write 64bit integer in little-endian byte order
           write(f,htol(Int64(42)))
       end
8

julia> open(fname,"r") do f
           # Convert back to host byte order and host integer type
           Int(ltoh(read(f,Int64)))
       end
42
```

Merging write calls:

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."

julia> write(io, "Sometimes those members") + write(io, " write documentation.")
44

julia> String(take!(io))
"Sometimes those members write documentation."
```

User-defined plain-data types without `write` methods can be written when wrapped in a `Ref`:

```jldoctest
julia> struct MyStruct; x::Float64; end

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, Ref(MyStruct(42.0)))
8

julia> seekstart(io); read!(io, Ref(MyStruct(NaN)))
Base.RefValue{MyStruct}(MyStruct(42.0))
```


In [42]:
io = IOBuffer();

In [43]:
write(io, "Hello.", " My name is Alyona")

24

In [44]:
write(io, "Hello.") + write(io, " My name is Alyona")

24

In [45]:
String(take!(io))

"Hello. My name is AlyonaHello. My name is Alyona"

In [46]:
parse(Int, "14")

14

In [47]:
parse(Int, "11011", base = 2)

27

In [48]:
parse(Int, "4fe", base = 16)

1278

In [49]:
parse(Float64, "314e-2")

3.14

In [50]:
a = 3 + 1
b = 4 * 1.5
c = "Alyona " * "hello"
println(a, '\n', b, '\n', c)

4
6.0
Alyona hello


In [51]:
a = 6 - 4
b = 3.2 - 2.2
println(a, '\n', b)

2
1.0


In [52]:
a = 8/2
b = 4/10
println(a, '\n', b)

4.0
0.4


In [53]:
a = 3^2
b = 7^0.3
println(a, '\n', b)

9
1.792789962520997


In [54]:
a = sqrt(121)
b = sqrt(64)
println(a, '\n', b)

11.0
8.0


In [55]:
a = 8 < 9
b = 1 > 2
c = 5 == 5
d = 6 != 4
println(a, '\n', b, '\n', c, '\n', d)

true
false
true
true


In [56]:
a = true && false
b = true && true
println(a, '\n', b)

false
true


In [57]:
a = true || false
b = true || true
println(a, '\n', b)

true
true


In [58]:
a = !true
b = !false
println(a, '\n', b)

false
true


In [59]:
A = [3 2; 1 0]
B = [1 2; 4 1]
C = A + B

2×2 Matrix{Int64}:
 4  4
 5  1

In [60]:
A = [3 2; 9 5]
B = [1 2; 4 1]
C = A - B

2×2 Matrix{Int64}:
 2  0
 5  4

In [61]:
A = [3 2; 1 0]
B = [1 2; 4 1]
C = A * B

2×2 Matrix{Int64}:
 11  8
  1  2

In [62]:
A = [3 2; 1 0]
k = 4
C = A * k

2×2 Matrix{Int64}:
 12  8
  4  0

In [63]:
A

2×2 Matrix{Int64}:
 3  2
 1  0

In [64]:
A'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 3  1
 2  0

In [65]:
using LinearAlgebra
u = [1, 3, 4]
v = [3, 1, 2]
c = dot(u, v)

14

In [66]:
using LinearAlgebra
u = [1, 3, 4]
v = [3, 1, 2]
c = cross(u, v)

3-element Vector{Int64}:
  2
 10
 -8